[package]
authors = ["trevp", "sopium"]
license = "Unlicense"
name = "noise-protocol"
readme = "README.md"
repository = "https://github.com/sopium/noise-rust"
version = "0.0.1"
description = "Noise Protocol Framework implementation"
keywords = ["noise"]
categories = ["cryptography"]

[dependencies]
rand = "0.3"
