[package]
authors = ["trevp", "sopium"]
license = "Unlicense"
name = "noise-protocol"
readme = "README.md"
repository = "https://github.com/sopium/noise-rust"
version = "0.0.2"
description = "Noise Protocol Framework implementation."
keywords = ["noise"]
categories = ["cryptography"]
documentation = "https://docs.rs/noise-protocol/0.0.2"
