sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly

install:
  - rustup component add rustfmt

script:
  - cargo fmt -- --check
  - cd noise && cargo check --no-default-features
  - cargo test --all --verbose
