[package]
name = "noise"
version = "0.1.0"
authors = ["trevp", "sopium"]

[dependencies]
rust-crypto = "0.2"
byteorder = "1.0"
rand = "0.3"

[dev-dependencies]
rustc-serialize = "0.3"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
