[package]
authors = ["sopium <sopium@mysterious.site>"]
license = "Unlicense"
name = "noise-sodiumoxide"
readme = "README.md"
repository = "https://github.com/sopium/noise-rust"
version = "0.0.3"
description = "Sodiumoxide wrappers for noise-protocol."
documentation = "https://docs.rs/noise-sodiumoxide/0.0.3"

[dependencies]
byteorder = "1.0.0"
libsodium-sys = "0.0.16"
noise-protocol = { version = "0.0.3", path = "../noise" }
sodiumoxide = "0.0.16"
